
 name: auto code merge 
 on:
  workflow_dispatch:
    inputs:
      codemerge:
        description: 'dev to stage code merge'
        required: true
        default: 'main'
        type: choice
        options:
        - yes
        - no
 jobs:
  merge-branch:
    runs-on: ubuntu-latest
      steps:
      - name: Set Git user info
        run: |
          git config --global user.email "ravinathb8325@gmail.com"
          git config --global user.name "ravinadh777"

          repository: ravinadh777-trail
          token: "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"


      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: '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'
          source_ref: 'develop'
          target_branch: 'staging'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
